---
- name: Install and Configure Monitoring Tools (Prometheus and Grafana)
  hosts: aws_ec2
  become: yes
  tasks:
    # CloudWatch Exporter Configuration
    - name: Create CloudWatch Exporter configuration directory
      file:
        path: /etc/prometheus/cloudwatch_exporter
        state: directory

    - name: Create CloudWatch Exporter configuration file
      copy:
        content: |
          region: us-east-1
          metrics:
            - aws_namespace: AWS/ELB
              aws_metric_name: RequestCount
              aws_dimensions: [LoadBalancerName]
              aws_dimension_select:
                LoadBalancerName: ["a894facca31e7414a98522d544a27fbb"]
              aws_statistics: [Sum]
        dest: /etc/prometheus/cloudwatch_exporter/config.yml

    - name: Deploy CloudWatch Exporter
      docker_container:
        name: cloudwatch_exporter
        image: prom/cloudwatch-exporter:latest
        ports:
          - "9106:9106"
        volumes:
          - /etc/prometheus/cloudwatch_exporter/config.yml:/config/config.yml:ro
        restart_policy: unless-stopped

    # Prometheus Configuration
    - name: Create Prometheus configuration directory
      file:
        path: /etc/prometheus
        state: directory

    - name: Create Prometheus configuration file
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'kubernetes-pods'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_label_app]
                  action: keep
                  regex: store-app-deploy  # Adjust this regex to match your application label
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                  action: keep
                  regex: "true"
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                  action: replace
                  target_label: __metrics_path__
                  regex: (.+)
                - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                  action: replace
                  regex: ([^:]+)(?::\d+)?;(\d+)
                  replacement: $1:$2
                  target_label: __address__

            - job_name: 'cloudwatch'
              scrape_interval: 1m
              static_configs:
                - targets: ['172.17.0.4:9106']  # Use the service name for DNS resolution

    # Deploy Prometheus
    - name: Install and start Prometheus
      docker_container:
        name: prometheus
        image: prom/prometheus:v2.26.0
        ports:
          - "9090:9090"
        volumes:
          - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        state: started
        restart_policy: unless-stopped

    # Grafana Configuration
    - name: Install and start Grafana
      docker_container:
        name: grafana
        image: grafana/grafana:7.5.0
        ports:
          - "3000:3000"
        state: started
        restart_policy: unless-stopped
