---
- name: Setup CloudWatch Monitoring for EKS and ELB
  hosts: aws_ec2
  become: yes
  vars:
    aws_region: us-east-1
    eks_cluster_name: devops-eks-cluster
    elb_name: a894facca31e7414a98522d544a27fbb

  tasks:
    - name: Install CloudWatch Agent
      shell: |
        wget https://s3.amazonaws.com/amazoncloudwatch-agent/linux/amd64/latest/AmazonCloudWatchAgent.zip
        unzip AmazonCloudWatchAgent.zip -d /tmp
        /tmp/install.sh

    - name: Configure CloudWatch Agent for EKS and ELB Monitoring
      template:
        src: cloudwatch-agent-config.json.j2
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json

    - name: Start CloudWatch Agent
      command: systemctl start amazon-cloudwatch-agent